### ISSUE TITLE
Multiple "'FabricScript' object has no attribute" errors

### ISSUE THREAD

**Issue by Gushousekai195** [dvruette/sd-webui-fabric#17]
```
Error calling: C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py/ui
Traceback (most recent call last):
  File "C:\Users\mattb\stable-diffusion-webui\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 158, in ui
    like_btn_selected.click(self.add_image_to_state, inputs=[self.selected_txt2img_image, liked_images], outputs=[liked_images, like_gallery])
AttributeError: 'FabricScript' object has no attribute 'selected_txt2img_image'

Error calling: C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py/ui
Traceback (most recent call last):
  File "C:\Users\mattb\stable-diffusion-webui\modules\scripts.py", line 283, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 151, in ui
    WebUiComponents.on_txt2img_gallery(self.register_txt2img_gallery_select)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\helpers.py", line 11, in on_txt2img_gallery
    callback(WebUiComponents.txt2img_gallery)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 244, in register_txt2img_gallery_select
    display=self.txt2img_selected_display,
AttributeError: 'FabricScript' object has no attribute 'txt2img_selected_display'

Error executing callback after_component_callback for C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py
Traceback (most recent call last):
  File "C:\Users\mattb\stable-diffusion-webui\modules\script_callbacks.py", line 225, in after_component_callback
    c.callback(component, **kwargs)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\helpers.py", line 32, in register_component
    callback(component)
  File "C:\Users\mattb\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 252, in register_img2img_gallery_select
    display=self.img2img_selected_display,
AttributeError: 'FabricScript' object has no attribute 'img2img_selected_display'
```

**Comment by Gushousekai195** [comment]
> Does this happen on the txt2img tab or the img2img tab?

It happens when starting the webui in the cmd

**Comment by dvruette** [comment]
Should now be fixed.
