### ISSUE TITLE
ImportError: cannot import name 'create_refresh_button' from 'modules.ui_common'

### ISSUE THREAD

**Issue by h3rmit-git** [dvruette/sd-webui-fabric#22]
I am getting the following error during startup of WebUI after installing the FABRIC plugin.

Error loading script: fabric.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py", line 15, in <module>
    from modules.ui_common import create_refresh_button
ImportError: cannot import name 'create_refresh_button' from 'modules.ui_common'
 (E:\stable-diffusion-webui\modules\ui_common.py)

I am using Stable-Diffusion-WebUI v1.3.0.

**Comment by dvruette** [comment]
It seems to be a compatibility issue between FABRIC and WebUI v1.3.0. I’ll have a look and see if I can make the plugin backwards compatible, but in the meantime everything should work if you update the WebUI to v1.5.x.

**Comment by h3rmit-git** [comment]
I went ahead and added backward compatibility with WebUI v1.3.0 and (probably) earlier versions.

I've opened a Pull Request here:
https://github.com/dvruette/sd-webui-fabric/pull/23

**Comment by dvruette** [comment]
Merged it, thanks a lot for the fix!
