### ISSUE TITLE
FABRIC is incompatible with sd-webui-roop

### ISSUE THREAD

**Issue by swumagic** [dvruette/sd-webui-fabric#30]
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\git\sdxlwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 23, in <module>
        from scripts.helpers import make_grid
    ImportError: cannot import name 'make_grid' from 'scripts.helpers' (M:\SD\git\sdxlwebui\extensions\sd-webui-fabric\scripts\helpers.py)

**Comment by dvruette** [comment]
This seems to be an incompatibility with your `sd-webui-roop-nsfw` extension. I can't find this extension anywhere online, so I'm not sure how it can be fixed. I'll push a change that will hopefully address conflicts like this, but in general I only plan on supporting compatibility to major plugins, which this one doesn't seem to be.

**Comment by swumagic** [comment]
sd-webui-roop-nsfw：git clone https://github.com/Gourieff/sd-webui-reactor

**Comment by dvruette** [comment]
I've pushed a fix, please try updating to the newest version and lmk if it's working.
