### ISSUE TITLE
Doesn't work using Webui Forge

### ISSUE THREAD

**Issue by tomasforsman** [dvruette/sd-webui-fabric#37]
Only way to get it to work is to run forge webui with --always-cpu. Running no other extensions except those built into forge.

Begin to load 1 model
Model loaded in 2.1s (unload existing model: 0.3s, forge load real models: 1.2s, load VAE: 0.4s, calculate empty prompt: 0.1s).
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.35 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.35it/s]
To load target model AutoencoderKL████████████████████                                 | 20/40 [00:01<00:01, 16.58it/s]
Begin to load 1 model
Moving model(s) has taken 0.14 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 17.76it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:02<00:00, 13.43it/s]
[FABRIC] Patching U-Net forward pass... (1 likes, 1 dislikes)██████████████████████████| 40/40 [00:02<00:00, 17.15it/s]
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\StableDiffusion\forgeui\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "C:\StableDiffusion\forgeui\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\StableDiffusion\forgeui\webui\modules\txt2img.py", line 111, in txt2img_function
    processed = processing.process_images(p)
  File "C:\StableDiffusion\forgeui\webui\modules\processing.py", line 752, in process_images
    res = process_images_inner(p)
  File "C:\StableDiffusion\forgeui\webui\modules\processing.py", line 923, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\StableDiffusion\forgeui\webui\extensions\sd-webui-fabric\scripts\marking.py", line 29, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\webui\modules\processing.py", line 1273, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\StableDiffusion\forgeui\webui\modules\sd_samplers_kdiffusion.py", line 251, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\StableDiffusion\forgeui\webui\modules\sd_samplers_common.py", line 263, in launch_sampling
    return func()
  File "C:\StableDiffusion\forgeui\webui\modules\sd_samplers_kdiffusion.py", line 251, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\StableDiffusion\forgeui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\StableDiffusion\forgeui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\webui\modules\sd_samplers_cfg_denoiser.py", line 182, in forward
    denoised = forge_sampler.forge_sample(self, denoiser_params=denoiser_params,
  File "C:\StableDiffusion\forgeui\webui\modules_forge\forge_sampler.py", line 83, in forge_sample
    denoised = sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options, seed)
  File "C:\StableDiffusion\forgeui\webui\ldm_patched\modules\samplers.py", line 289, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "C:\StableDiffusion\forgeui\webui\ldm_patched\modules\samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\StableDiffusion\forgeui\webui\ldm_patched\modules\model_base.py", line 89, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\StableDiffusion\forgeui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\StableDiffusion\forgeui\webui\extensions\sd-webui-fabric\scripts\patching.py", line 137, in new_forward
    z = p.sd_model.q_sample(latent.unsqueeze(0), torch.round(timesteps.float()).long())[0]
  File "C:\StableDiffusion\forgeui\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 356, in q_sample
    return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_start +
  File "C:\StableDiffusion\forgeui\webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 105, in extract_into_tensor
    out = a.gather(-1, t)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA_gather)
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA_gather)
*** Error completing request
*** Arguments: ('task(n4489af1ygyr80u)', <gradio.routes.Request object at 0x00000249E65596C0>, 'portrait', '', [], 20, 'DPM++ 2M Karras', 2, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, ['345d89fe2353513d.png'], ['18e118a461f95b68.png'], True, 0, 0.8, 0, 0.8, 0.5, False, False, 0.5, 8192, -1.0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], generated_image=None, mask_image=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\StableDiffusion\forgeui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

**Comment by LindezaBlue** [comment]
same here. +1

**Comment by dvruette** [comment]
Thanks for opening this issue, it should now be fixed (as of v0.6.5).

**Comment by akaikite** [comment]
> Thanks for opening this issue, it should now be fixed (as of v0.6.5).



I am using forge and found that this error occurs.
Please see below
------

  File "/home/pinkman/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/pinkman/.local/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 339, in _memory_efficient_attention_forward
    _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)
  File "/home/pinkman/.local/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 39, in _ensure_op_supports_or_raise
    raise exc_type(
ValueError: Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(2, 3952, 10, 64) (torch.float16)
     key         : shape=(2, 11856, 10, 64) (torch.float16)
     value       : shape=(2, 11856, 10, 64) (torch.float16)
     attn_bias   : <class 'torch.Tensor'>
     p           : 0.0
`flshattF@v2.3.6` is not supported because:
    attn_bias type is <class 'torch.Tensor'>
Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(2, 3952, 10, 64) (torch.float16)
     key         : shape=(2, 11856, 10, 64) (torch.float16)
     value       : shape=(2, 11856, 10, 64) (torch.float16)
     attn_bias   : <class 'torch.Tensor'>
     p           : 0.0
`flshattF@v2.3.6` is not supported because:
    attn_bias type is <class 'torch.Tensor'>
