### ISSUE TITLE
slice error with SDXL

### ISSUE THREAD

**Issue by thibaudart** [dvruette/sd-webui-fabric#9]
[FABRIC] Skipping U-Net forward pass patching
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.65it/s]
[FABRIC] Restoring original U-Net forward pass█████████████████████████████████████████| 20/20 [00:05<00:00,  3.22it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.02it/s]
[FABRIC] Skipping U-Net forward pass patching██████████████████████████████████████████| 20/20 [00:06<00:00,  3.22it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.22s/it]
[FABRIC] Restoring original U-Net forward pass█████████████████████████████████████████| 20/20 [00:23<00:00,  1.22s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.33s/it]
[FABRIC] Patching U-Net forward pass...████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.22s/it]
*** Error completing request
*** Arguments: ('task(r33wg6x41bgfb9n)', 'portrait', 'bad art, low res', [], 20, 0, False, False, 1, 4, 7, -1.0, -1.0, 0, 0, 0, False, 1024, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x000002D7AD652620>, 0, [<PIL.Image.Image image mode=RGB size=1024x1024 at 0x2D79C4E4250>, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x2D79C42CAF0>], [<PIL.Image.Image image mode=RGB size=1024x1024 at 0x2D7AD248070>, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x2D7AD24ACB0>, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x2D79C42C1F0>], False, 4, 0, 0.8, 0, 0.8, 0.5, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "E:\automatic_xl\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "E:\automatic_xl\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "E:\automatic_xl\modules\txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "E:\automatic_xl\modules\processing.py", line 673, in process_images
        res = process_images_inner(p)
      File "E:\automatic_xl\modules\processing.py", line 793, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 24, in process_sample
        mark_prompt_context(kwargs.get('conditioning', []), positive=True)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 44, in mark_prompt_context
        x.batch = mark_prompt_context(x.batch, positive)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 41, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 41, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 47, in mark_prompt_context
        x.schedules = mark_prompt_context(x.schedules, positive)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 41, in mark_prompt_context
        x[i] = mark_prompt_context(x[i], positive)
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 51, in mark_prompt_context
        if prompt_context_is_marked(cond):
      File "E:\automatic_xl\extensions\sd-webui-fabric\scripts\marking.py", line 32, in prompt_context_is_marked
        t = x[..., 0, :]
    TypeError: unhashable type: 'slice'

**Comment by dvruette** [comment]
Yes, this is most likely a SDXL issue. FABRIC has not been tested for compatibility with SDXL yet and it might be a while until we have time to look into it.

**Comment by dvruette** [comment]
I've finally gotten around to adding SDXL support, should be fixed in v0.6.4.
